# 00-kyoto-hardening.conf

# Who should have access?
AllowUsers      nstrm
PermitRootLogin no

# How should you be able to login?
PasswordAuthentication       no
AuthenticationMethods        publickey
KbdInteractiveAuthentication no
PermitEmptyPasswords         no
