# /opt/docker/arcane/compose.yml

services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    container_name: arcane
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/arcane:/app/data
      - /opt/docker:/opt/docker

    environment:
      APP_URL: ${APP_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PROJECTS_DIRECTORY: ${PROJECTS_DIRECTORY}
      PUID: ${PUID}
      PGID: ${PGID}

    networks:
      - cloudflared

    healthcheck:
      test: ["CMD", "./arcane", "health", "--timeout", "2s"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

networks:
  cloudflared:
    external: true
