# /opt/docker/arcane/compose.yml

services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.10.2
    container_name: arcane
    restart: unless-stopped
    # Help Arcane identify its own container when performing self-upgrades.
    cgroup: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/arcane:/app/data
      - /opt/docker:/opt/docker
      # Supply a static shell directly from an image.
      - type: image
        source: busybox:1.38.0-musl
        target: /opt/arcane-shell
        read_only: true
        image:
          subpath: bin

    environment:
      PATH: /app:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/arcane-shell
      APP_URL: ${APP_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PROJECTS_DIRECTORY: ${PROJECTS_DIRECTORY}
      PUID: ${PUID}
      PGID: ${PGID}

    networks:
      - cloudflared

    healthcheck:
      test: ["CMD", "./arcane", "health", "--timeout", "2s"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

networks:
  cloudflared:
    external: true
