# /opt/docker/cloudflared/compose.yml

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    command: tunnel --no-autoupdate run

    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}

    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
